// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/message.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CalculateTypes int32

const (
	CalculateTypes_INTEGER32 CalculateTypes = 0
	CalculateTypes_INTEGER64 CalculateTypes = 1
	CalculateTypes_FLOAT32   CalculateTypes = 2
	CalculateTypes_FLOAT64   CalculateTypes = 3
)

var CalculateTypes_name = map[int32]string{
	0: "INTEGER32",
	1: "INTEGER64",
	2: "FLOAT32",
	3: "FLOAT64",
}

var CalculateTypes_value = map[string]int32{
	"INTEGER32": 0,
	"INTEGER64": 1,
	"FLOAT32":   2,
	"FLOAT64":   3,
}

func (x CalculateTypes) String() string {
	return proto.EnumName(CalculateTypes_name, int32(x))
}

func (CalculateTypes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2c716e67c403b1b, []int{0}
}

type CalcRes_CalcStatus int32

const (
	CalcRes_OK    CalcRes_CalcStatus = 0
	CalcRes_ERROR CalcRes_CalcStatus = 1
)

var CalcRes_CalcStatus_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}

var CalcRes_CalcStatus_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x CalcRes_CalcStatus) String() string {
	return proto.EnumName(CalcRes_CalcStatus_name, int32(x))
}

func (CalcRes_CalcStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2c716e67c403b1b, []int{5, 0}
}

type Message_MessageType int32

const (
	Message_REGISTER_REQ  Message_MessageType = 0
	Message_REGISTER_RES  Message_MessageType = 1
	Message_HEARTBEAT_REQ Message_MessageType = 2
	Message_HEARTBEAT_RES Message_MessageType = 3
	Message_QUERY_REQ     Message_MessageType = 4
	Message_QUERY_RES     Message_MessageType = 5
	Message_CALCULATE_REQ Message_MessageType = 6
	Message_CALCULATE_RES Message_MessageType = 7
)

var Message_MessageType_name = map[int32]string{
	0: "REGISTER_REQ",
	1: "REGISTER_RES",
	2: "HEARTBEAT_REQ",
	3: "HEARTBEAT_RES",
	4: "QUERY_REQ",
	5: "QUERY_RES",
	6: "CALCULATE_REQ",
	7: "CALCULATE_RES",
}

var Message_MessageType_value = map[string]int32{
	"REGISTER_REQ":  0,
	"REGISTER_RES":  1,
	"HEARTBEAT_REQ": 2,
	"HEARTBEAT_RES": 3,
	"QUERY_REQ":     4,
	"QUERY_RES":     5,
	"CALCULATE_REQ": 6,
	"CALCULATE_RES": 7,
}

func (x Message_MessageType) String() string {
	return proto.EnumName(Message_MessageType_name, int32(x))
}

func (Message_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2c716e67c403b1b, []int{6, 0}
}

type CalcReq struct {
	Type CalculateTypes `protobuf:"varint,1,opt,name=Type,proto3,enum=protos.CalculateTypes" json:"Type,omitempty"`
	// Types that are valid to be assigned to Op1:
	//	*CalcReq_Int32Op1
	//	*CalcReq_Int64Op1
	//	*CalcReq_Float32Op1
	//	*CalcReq_Float64Op1
	Op1 isCalcReq_Op1 `protobuf_oneof:"op1"`
	// Types that are valid to be assigned to Op2:
	//	*CalcReq_Int32Op2
	//	*CalcReq_Int64Op2
	//	*CalcReq_Float32Op2
	//	*CalcReq_Float64Op2
	Op2                  isCalcReq_Op2 `protobuf_oneof:"op2"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CalcReq) Reset()         { *m = CalcReq{} }
func (m *CalcReq) String() string { return proto.CompactTextString(m) }
func (*CalcReq) ProtoMessage()    {}
func (*CalcReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2c716e67c403b1b, []int{0}
}

func (m *CalcReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalcReq.Unmarshal(m, b)
}
func (m *CalcReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalcReq.Marshal(b, m, deterministic)
}
func (m *CalcReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalcReq.Merge(m, src)
}
func (m *CalcReq) XXX_Size() int {
	return xxx_messageInfo_CalcReq.Size(m)
}
func (m *CalcReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CalcReq.DiscardUnknown(m)
}

var xxx_messageInfo_CalcReq proto.InternalMessageInfo

func (m *CalcReq) GetType() CalculateTypes {
	if m != nil {
		return m.Type
	}
	return CalculateTypes_INTEGER32
}

type isCalcReq_Op1 interface {
	isCalcReq_Op1()
}

type CalcReq_Int32Op1 struct {
	Int32Op1 int32 `protobuf:"varint,3,opt,name=int32op1,proto3,oneof"`
}

type CalcReq_Int64Op1 struct {
	Int64Op1 int64 `protobuf:"varint,4,opt,name=int64op1,proto3,oneof"`
}

type CalcReq_Float32Op1 struct {
	Float32Op1 float32 `protobuf:"fixed32,5,opt,name=float32op1,proto3,oneof"`
}

type CalcReq_Float64Op1 struct {
	Float64Op1 float64 `protobuf:"fixed64,6,opt,name=float64op1,proto3,oneof"`
}

func (*CalcReq_Int32Op1) isCalcReq_Op1() {}

func (*CalcReq_Int64Op1) isCalcReq_Op1() {}

func (*CalcReq_Float32Op1) isCalcReq_Op1() {}

func (*CalcReq_Float64Op1) isCalcReq_Op1() {}

func (m *CalcReq) GetOp1() isCalcReq_Op1 {
	if m != nil {
		return m.Op1
	}
	return nil
}

func (m *CalcReq) GetInt32Op1() int32 {
	if x, ok := m.GetOp1().(*CalcReq_Int32Op1); ok {
		return x.Int32Op1
	}
	return 0
}

func (m *CalcReq) GetInt64Op1() int64 {
	if x, ok := m.GetOp1().(*CalcReq_Int64Op1); ok {
		return x.Int64Op1
	}
	return 0
}

func (m *CalcReq) GetFloat32Op1() float32 {
	if x, ok := m.GetOp1().(*CalcReq_Float32Op1); ok {
		return x.Float32Op1
	}
	return 0
}

func (m *CalcReq) GetFloat64Op1() float64 {
	if x, ok := m.GetOp1().(*CalcReq_Float64Op1); ok {
		return x.Float64Op1
	}
	return 0
}

type isCalcReq_Op2 interface {
	isCalcReq_Op2()
}

type CalcReq_Int32Op2 struct {
	Int32Op2 int32 `protobuf:"varint,7,opt,name=int32op2,proto3,oneof"`
}

type CalcReq_Int64Op2 struct {
	Int64Op2 int64 `protobuf:"varint,8,opt,name=int64op2,proto3,oneof"`
}

type CalcReq_Float32Op2 struct {
	Float32Op2 float32 `protobuf:"fixed32,9,opt,name=float32op2,proto3,oneof"`
}

type CalcReq_Float64Op2 struct {
	Float64Op2 float64 `protobuf:"fixed64,10,opt,name=float64op2,proto3,oneof"`
}

func (*CalcReq_Int32Op2) isCalcReq_Op2() {}

func (*CalcReq_Int64Op2) isCalcReq_Op2() {}

func (*CalcReq_Float32Op2) isCalcReq_Op2() {}

func (*CalcReq_Float64Op2) isCalcReq_Op2() {}

func (m *CalcReq) GetOp2() isCalcReq_Op2 {
	if m != nil {
		return m.Op2
	}
	return nil
}

func (m *CalcReq) GetInt32Op2() int32 {
	if x, ok := m.GetOp2().(*CalcReq_Int32Op2); ok {
		return x.Int32Op2
	}
	return 0
}

func (m *CalcReq) GetInt64Op2() int64 {
	if x, ok := m.GetOp2().(*CalcReq_Int64Op2); ok {
		return x.Int64Op2
	}
	return 0
}

func (m *CalcReq) GetFloat32Op2() float32 {
	if x, ok := m.GetOp2().(*CalcReq_Float32Op2); ok {
		return x.Float32Op2
	}
	return 0
}

func (m *CalcReq) GetFloat64Op2() float64 {
	if x, ok := m.GetOp2().(*CalcReq_Float64Op2); ok {
		return x.Float64Op2
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CalcReq) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CalcReq_Int32Op1)(nil),
		(*CalcReq_Int64Op1)(nil),
		(*CalcReq_Float32Op1)(nil),
		(*CalcReq_Float64Op1)(nil),
		(*CalcReq_Int32Op2)(nil),
		(*CalcReq_Int64Op2)(nil),
		(*CalcReq_Float32Op2)(nil),
		(*CalcReq_Float64Op2)(nil),
	}
}

//定义四种返回值类型字段
type Int32Ans struct {
	AddInt32             int32    `protobuf:"zigzag32,1,opt,name=AddInt32,proto3" json:"AddInt32,omitempty"`
	MinInt32             int32    `protobuf:"zigzag32,2,opt,name=MinInt32,proto3" json:"MinInt32,omitempty"`
	MulInt32             int32    `protobuf:"zigzag32,3,opt,name=MulInt32,proto3" json:"MulInt32,omitempty"`
	DivInt32             int32    `protobuf:"zigzag32,4,opt,name=DivInt32,proto3" json:"DivInt32,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int32Ans) Reset()         { *m = Int32Ans{} }
func (m *Int32Ans) String() string { return proto.CompactTextString(m) }
func (*Int32Ans) ProtoMessage()    {}
func (*Int32Ans) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2c716e67c403b1b, []int{1}
}

func (m *Int32Ans) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int32Ans.Unmarshal(m, b)
}
func (m *Int32Ans) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int32Ans.Marshal(b, m, deterministic)
}
func (m *Int32Ans) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int32Ans.Merge(m, src)
}
func (m *Int32Ans) XXX_Size() int {
	return xxx_messageInfo_Int32Ans.Size(m)
}
func (m *Int32Ans) XXX_DiscardUnknown() {
	xxx_messageInfo_Int32Ans.DiscardUnknown(m)
}

var xxx_messageInfo_Int32Ans proto.InternalMessageInfo

func (m *Int32Ans) GetAddInt32() int32 {
	if m != nil {
		return m.AddInt32
	}
	return 0
}

func (m *Int32Ans) GetMinInt32() int32 {
	if m != nil {
		return m.MinInt32
	}
	return 0
}

func (m *Int32Ans) GetMulInt32() int32 {
	if m != nil {
		return m.MulInt32
	}
	return 0
}

func (m *Int32Ans) GetDivInt32() int32 {
	if m != nil {
		return m.DivInt32
	}
	return 0
}

type Int64Ans struct {
	AddInt64             int64    `protobuf:"zigzag64,1,opt,name=AddInt64,proto3" json:"AddInt64,omitempty"`
	MinInt64             int64    `protobuf:"zigzag64,2,opt,name=MinInt64,proto3" json:"MinInt64,omitempty"`
	MulInt64             int64    `protobuf:"zigzag64,3,opt,name=MulInt64,proto3" json:"MulInt64,omitempty"`
	DivInt64             int64    `protobuf:"zigzag64,4,opt,name=DivInt64,proto3" json:"DivInt64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64Ans) Reset()         { *m = Int64Ans{} }
func (m *Int64Ans) String() string { return proto.CompactTextString(m) }
func (*Int64Ans) ProtoMessage()    {}
func (*Int64Ans) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2c716e67c403b1b, []int{2}
}

func (m *Int64Ans) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64Ans.Unmarshal(m, b)
}
func (m *Int64Ans) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64Ans.Marshal(b, m, deterministic)
}
func (m *Int64Ans) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64Ans.Merge(m, src)
}
func (m *Int64Ans) XXX_Size() int {
	return xxx_messageInfo_Int64Ans.Size(m)
}
func (m *Int64Ans) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64Ans.DiscardUnknown(m)
}

var xxx_messageInfo_Int64Ans proto.InternalMessageInfo

func (m *Int64Ans) GetAddInt64() int64 {
	if m != nil {
		return m.AddInt64
	}
	return 0
}

func (m *Int64Ans) GetMinInt64() int64 {
	if m != nil {
		return m.MinInt64
	}
	return 0
}

func (m *Int64Ans) GetMulInt64() int64 {
	if m != nil {
		return m.MulInt64
	}
	return 0
}

func (m *Int64Ans) GetDivInt64() int64 {
	if m != nil {
		return m.DivInt64
	}
	return 0
}

type Float32Ans struct {
	AddFloat32           float32  `protobuf:"fixed32,1,opt,name=AddFloat32,proto3" json:"AddFloat32,omitempty"`
	MinFloat32           float32  `protobuf:"fixed32,2,opt,name=MinFloat32,proto3" json:"MinFloat32,omitempty"`
	MulFloat32           float32  `protobuf:"fixed32,3,opt,name=MulFloat32,proto3" json:"MulFloat32,omitempty"`
	DivFloat32           float32  `protobuf:"fixed32,4,opt,name=DivFloat32,proto3" json:"DivFloat32,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Float32Ans) Reset()         { *m = Float32Ans{} }
func (m *Float32Ans) String() string { return proto.CompactTextString(m) }
func (*Float32Ans) ProtoMessage()    {}
func (*Float32Ans) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2c716e67c403b1b, []int{3}
}

func (m *Float32Ans) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Float32Ans.Unmarshal(m, b)
}
func (m *Float32Ans) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Float32Ans.Marshal(b, m, deterministic)
}
func (m *Float32Ans) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Float32Ans.Merge(m, src)
}
func (m *Float32Ans) XXX_Size() int {
	return xxx_messageInfo_Float32Ans.Size(m)
}
func (m *Float32Ans) XXX_DiscardUnknown() {
	xxx_messageInfo_Float32Ans.DiscardUnknown(m)
}

var xxx_messageInfo_Float32Ans proto.InternalMessageInfo

func (m *Float32Ans) GetAddFloat32() float32 {
	if m != nil {
		return m.AddFloat32
	}
	return 0
}

func (m *Float32Ans) GetMinFloat32() float32 {
	if m != nil {
		return m.MinFloat32
	}
	return 0
}

func (m *Float32Ans) GetMulFloat32() float32 {
	if m != nil {
		return m.MulFloat32
	}
	return 0
}

func (m *Float32Ans) GetDivFloat32() float32 {
	if m != nil {
		return m.DivFloat32
	}
	return 0
}

type Float64Ans struct {
	AddFloat64           float64  `protobuf:"fixed64,1,opt,name=AddFloat64,proto3" json:"AddFloat64,omitempty"`
	MinFloat64           float64  `protobuf:"fixed64,2,opt,name=MinFloat64,proto3" json:"MinFloat64,omitempty"`
	MulFloat64           float64  `protobuf:"fixed64,3,opt,name=MulFloat64,proto3" json:"MulFloat64,omitempty"`
	DivFloat64           float64  `protobuf:"fixed64,4,opt,name=DivFloat64,proto3" json:"DivFloat64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Float64Ans) Reset()         { *m = Float64Ans{} }
func (m *Float64Ans) String() string { return proto.CompactTextString(m) }
func (*Float64Ans) ProtoMessage()    {}
func (*Float64Ans) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2c716e67c403b1b, []int{4}
}

func (m *Float64Ans) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Float64Ans.Unmarshal(m, b)
}
func (m *Float64Ans) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Float64Ans.Marshal(b, m, deterministic)
}
func (m *Float64Ans) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Float64Ans.Merge(m, src)
}
func (m *Float64Ans) XXX_Size() int {
	return xxx_messageInfo_Float64Ans.Size(m)
}
func (m *Float64Ans) XXX_DiscardUnknown() {
	xxx_messageInfo_Float64Ans.DiscardUnknown(m)
}

var xxx_messageInfo_Float64Ans proto.InternalMessageInfo

func (m *Float64Ans) GetAddFloat64() float64 {
	if m != nil {
		return m.AddFloat64
	}
	return 0
}

func (m *Float64Ans) GetMinFloat64() float64 {
	if m != nil {
		return m.MinFloat64
	}
	return 0
}

func (m *Float64Ans) GetMulFloat64() float64 {
	if m != nil {
		return m.MulFloat64
	}
	return 0
}

func (m *Float64Ans) GetDivFloat64() float64 {
	if m != nil {
		return m.DivFloat64
	}
	return 0
}

type CalcRes struct {
	Type   CalculateTypes     `protobuf:"varint,1,opt,name=Type,proto3,enum=protos.CalculateTypes" json:"Type,omitempty"`
	Status CalcRes_CalcStatus `protobuf:"varint,2,opt,name=Status,proto3,enum=protos.CalcRes_CalcStatus" json:"Status,omitempty"`
	// Types that are valid to be assigned to Result:
	//	*CalcRes_Int32Ans
	//	*CalcRes_Int64Ans
	//	*CalcRes_Float32Ans
	//	*CalcRes_Float64Ans
	Result               isCalcRes_Result `protobuf_oneof:"Result"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CalcRes) Reset()         { *m = CalcRes{} }
func (m *CalcRes) String() string { return proto.CompactTextString(m) }
func (*CalcRes) ProtoMessage()    {}
func (*CalcRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2c716e67c403b1b, []int{5}
}

func (m *CalcRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalcRes.Unmarshal(m, b)
}
func (m *CalcRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalcRes.Marshal(b, m, deterministic)
}
func (m *CalcRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalcRes.Merge(m, src)
}
func (m *CalcRes) XXX_Size() int {
	return xxx_messageInfo_CalcRes.Size(m)
}
func (m *CalcRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CalcRes.DiscardUnknown(m)
}

var xxx_messageInfo_CalcRes proto.InternalMessageInfo

func (m *CalcRes) GetType() CalculateTypes {
	if m != nil {
		return m.Type
	}
	return CalculateTypes_INTEGER32
}

func (m *CalcRes) GetStatus() CalcRes_CalcStatus {
	if m != nil {
		return m.Status
	}
	return CalcRes_OK
}

type isCalcRes_Result interface {
	isCalcRes_Result()
}

type CalcRes_Int32Ans struct {
	Int32Ans *Int32Ans `protobuf:"bytes,3,opt,name=int32ans,proto3,oneof"`
}

type CalcRes_Int64Ans struct {
	Int64Ans *Int64Ans `protobuf:"bytes,4,opt,name=int64ans,proto3,oneof"`
}

type CalcRes_Float32Ans struct {
	Float32Ans *Float32Ans `protobuf:"bytes,5,opt,name=float32ans,proto3,oneof"`
}

type CalcRes_Float64Ans struct {
	Float64Ans *Float64Ans `protobuf:"bytes,6,opt,name=float64ans,proto3,oneof"`
}

func (*CalcRes_Int32Ans) isCalcRes_Result() {}

func (*CalcRes_Int64Ans) isCalcRes_Result() {}

func (*CalcRes_Float32Ans) isCalcRes_Result() {}

func (*CalcRes_Float64Ans) isCalcRes_Result() {}

func (m *CalcRes) GetResult() isCalcRes_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *CalcRes) GetInt32Ans() *Int32Ans {
	if x, ok := m.GetResult().(*CalcRes_Int32Ans); ok {
		return x.Int32Ans
	}
	return nil
}

func (m *CalcRes) GetInt64Ans() *Int64Ans {
	if x, ok := m.GetResult().(*CalcRes_Int64Ans); ok {
		return x.Int64Ans
	}
	return nil
}

func (m *CalcRes) GetFloat32Ans() *Float32Ans {
	if x, ok := m.GetResult().(*CalcRes_Float32Ans); ok {
		return x.Float32Ans
	}
	return nil
}

func (m *CalcRes) GetFloat64Ans() *Float64Ans {
	if x, ok := m.GetResult().(*CalcRes_Float64Ans); ok {
		return x.Float64Ans
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CalcRes) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CalcRes_Int32Ans)(nil),
		(*CalcRes_Int64Ans)(nil),
		(*CalcRes_Float32Ans)(nil),
		(*CalcRes_Float64Ans)(nil),
	}
}

type Message struct {
	MsgType Message_MessageType `protobuf:"varint,1,opt,name=msgType,proto3,enum=protos.Message_MessageType" json:"msgType,omitempty"`
	//可能返回的关于worker的socket信息
	Seq    int32  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Socket string `protobuf:"bytes,3,opt,name=socket,proto3" json:"socket,omitempty"`
	//注意这个socket复用了，在worker向master注册时用于表示自己的端口号，在client查询时，master返回的是worker的IP：Port
	Calcreq              *CalcReq `protobuf:"bytes,4,opt,name=calcreq,proto3" json:"calcreq,omitempty"`
	Calcres              *CalcRes `protobuf:"bytes,5,opt,name=calcres,proto3" json:"calcres,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2c716e67c403b1b, []int{6}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMsgType() Message_MessageType {
	if m != nil {
		return m.MsgType
	}
	return Message_REGISTER_REQ
}

func (m *Message) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Message) GetSocket() string {
	if m != nil {
		return m.Socket
	}
	return ""
}

func (m *Message) GetCalcreq() *CalcReq {
	if m != nil {
		return m.Calcreq
	}
	return nil
}

func (m *Message) GetCalcres() *CalcRes {
	if m != nil {
		return m.Calcres
	}
	return nil
}

func init() {
	proto.RegisterEnum("protos.CalculateTypes", CalculateTypes_name, CalculateTypes_value)
	proto.RegisterEnum("protos.CalcRes_CalcStatus", CalcRes_CalcStatus_name, CalcRes_CalcStatus_value)
	proto.RegisterEnum("protos.Message_MessageType", Message_MessageType_name, Message_MessageType_value)
	proto.RegisterType((*CalcReq)(nil), "protos.CalcReq")
	proto.RegisterType((*Int32Ans)(nil), "protos.Int32Ans")
	proto.RegisterType((*Int64Ans)(nil), "protos.Int64Ans")
	proto.RegisterType((*Float32Ans)(nil), "protos.Float32Ans")
	proto.RegisterType((*Float64Ans)(nil), "protos.Float64Ans")
	proto.RegisterType((*CalcRes)(nil), "protos.CalcRes")
	proto.RegisterType((*Message)(nil), "protos.Message")
}

func init() { proto.RegisterFile("protos/message.proto", fileDescriptor_c2c716e67c403b1b) }

var fileDescriptor_c2c716e67c403b1b = []byte{
	// 692 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xcd, 0xd8, 0x89, 0x93, 0xdc, 0xd2, 0xe2, 0x8e, 0x50, 0x15, 0x15, 0x04, 0x51, 0x56, 0xa1,
	0x8b, 0xa2, 0x4e, 0x8c, 0xf7, 0x6e, 0xeb, 0x36, 0x15, 0x2d, 0x55, 0x6f, 0xd2, 0x05, 0x2b, 0x64,
	0x12, 0x53, 0x45, 0xa4, 0x79, 0x74, 0x9c, 0x4a, 0xf0, 0x0d, 0xfc, 0x01, 0x9f, 0xc3, 0x7f, 0x20,
	0x3e, 0x05, 0xcd, 0xd3, 0x93, 0xc0, 0x86, 0x95, 0x7b, 0x1e, 0xd7, 0xe7, 0xf6, 0x64, 0x26, 0x81,
	0x67, 0x8b, 0x87, 0x79, 0x31, 0xe7, 0x6f, 0xee, 0x73, 0xce, 0xb3, 0xbb, 0xfc, 0x50, 0x42, 0x1a,
	0x28, 0xb6, 0xf3, 0xd3, 0x83, 0xfa, 0x49, 0x36, 0x1d, 0x61, 0xbe, 0xa4, 0x07, 0x50, 0x1d, 0x7e,
	0x5d, 0xe4, 0x2d, 0xd2, 0x26, 0xdd, 0x1d, 0xb6, 0xa7, 0x9c, 0xfc, 0x50, 0xc8, 0xab, 0x69, 0x56,
	0xe4, 0x42, 0xe4, 0x28, 0x3d, 0xf4, 0x05, 0x34, 0x26, 0xb3, 0xa2, 0xc7, 0xe6, 0x8b, 0xa3, 0x96,
	0xdf, 0x26, 0xdd, 0x5a, 0xbf, 0x82, 0x96, 0xd1, 0x6a, 0x1c, 0x09, 0xb5, 0xda, 0x26, 0x5d, 0x5f,
	0xab, 0x92, 0xa1, 0x6d, 0x80, 0xcf, 0xd3, 0x79, 0xa6, 0xa7, 0x6b, 0x6d, 0xd2, 0xf5, 0xfa, 0x15,
	0x74, 0x38, 0xeb, 0x50, 0x6f, 0x08, 0xda, 0xa4, 0x4b, 0xac, 0x43, 0xbd, 0xa3, 0xcc, 0x67, 0xad,
	0xba, 0xcc, 0x27, 0x36, 0x9f, 0x39, 0xf9, 0xac, 0xd5, 0x90, 0xf9, 0xc4, 0xe6, 0xb3, 0xb5, 0x7c,
	0xd6, 0x6a, 0xca, 0x7c, 0xe2, 0xe4, 0xb3, 0xb5, 0x7c, 0xd6, 0x02, 0x99, 0x4f, 0x9c, 0x7c, 0x76,
	0x5c, 0x03, 0x7f, 0xbe, 0x38, 0x52, 0x0f, 0xd6, 0xf9, 0x06, 0x8d, 0x0b, 0x91, 0x9d, 0xcc, 0x38,
	0xdd, 0x87, 0x46, 0x32, 0x1e, 0x4b, 0x28, 0x9b, 0xdc, 0x45, 0x8b, 0x85, 0x76, 0x35, 0x99, 0x29,
	0xcd, 0x53, 0x9a, 0xc1, 0x52, 0x5b, 0x4d, 0x95, 0xe6, 0x6b, 0x4d, 0x63, 0xa1, 0x9d, 0x4e, 0x1e,
	0x95, 0x56, 0x55, 0x9a, 0xc1, 0x3a, 0x3b, 0x8e, 0xd6, 0xb2, 0xe3, 0x48, 0x66, 0x53, 0xb4, 0xb8,
	0xcc, 0x8e, 0x23, 0x99, 0x4d, 0xd1, 0xe2, 0x32, 0x3b, 0x8e, 0x64, 0x36, 0x45, 0x8b, 0xcb, 0xec,
	0x38, 0x92, 0xd9, 0x14, 0x2d, 0xee, 0x7c, 0x27, 0x00, 0x67, 0xaa, 0x36, 0x11, 0xff, 0x12, 0x20,
	0x19, 0x8f, 0x35, 0x21, 0x17, 0xf0, 0xd0, 0x61, 0x84, 0x7e, 0x35, 0x99, 0x19, 0xdd, 0x53, 0x7a,
	0xc9, 0x48, 0x7d, 0x35, 0x35, 0xba, 0xaf, 0x75, 0xcb, 0x08, 0xfd, 0x74, 0xf2, 0x68, 0xf4, 0xaa,
	0xd2, 0x4b, 0xa6, 0x5c, 0x47, 0xb5, 0xe1, 0xac, 0xa3, 0xfb, 0x20, 0xe8, 0x30, 0xee, 0x3a, 0xba,
	0x13, 0x82, 0x0e, 0xe3, 0xae, 0xa3, 0x7b, 0x21, 0xe8, 0x30, 0xee, 0x3a, 0xba, 0x1b, 0x82, 0x0e,
	0xd3, 0xf9, 0x6d, 0xef, 0x16, 0xff, 0xaf, 0xbb, 0xc5, 0x20, 0x18, 0x14, 0x59, 0xb1, 0xe2, 0x72,
	0xa7, 0x1d, 0xb6, 0xef, 0xba, 0x31, 0x57, 0x4f, 0xe5, 0x40, 0xed, 0xa4, 0x87, 0xfa, 0x3e, 0x64,
	0x33, 0x2e, 0x37, 0xdd, 0x62, 0xa1, 0x99, 0x32, 0x27, 0xd3, 0xde, 0xd0, 0x6c, 0x66, 0xfc, 0x71,
	0x24, 0xfc, 0xd5, 0xbf, 0xfc, 0xb2, 0x3f, 0x7b, 0x67, 0x85, 0x3f, 0xb2, 0x77, 0x46, 0x4c, 0xd4,
	0xe4, 0x04, 0x35, 0x13, 0xe5, 0x11, 0x70, 0xee, 0xb1, 0x3b, 0xa5, 0x72, 0x82, 0x7f, 0x4c, 0x99,
	0x24, 0xc7, 0xd7, 0x79, 0x05, 0x50, 0xfe, 0x87, 0x34, 0x00, 0xef, 0xfa, 0x5d, 0x58, 0xa1, 0x4d,
	0xa8, 0xa5, 0x88, 0xd7, 0x18, 0x92, 0xe3, 0x06, 0x04, 0x98, 0xf3, 0xd5, 0xb4, 0xe8, 0xfc, 0xf2,
	0xa0, 0x7e, 0xa5, 0xbe, 0xd8, 0xe8, 0x5b, 0xa8, 0xdf, 0xf3, 0x3b, 0xa7, 0xe5, 0xe7, 0x26, 0x49,
	0x3b, 0xcc, 0x53, 0x58, 0xd0, 0x78, 0x69, 0x08, 0x3e, 0xcf, 0x97, 0xb2, 0xea, 0x1a, 0x8a, 0x3f,
	0xe9, 0x1e, 0x04, 0x7c, 0x3e, 0xfa, 0x92, 0x17, 0xb2, 0xc9, 0x26, 0x6a, 0x44, 0x5f, 0x43, 0x7d,
	0x94, 0x4d, 0x47, 0x0f, 0xf9, 0x52, 0x57, 0xf6, 0x74, 0xfd, 0x83, 0x59, 0xa2, 0xd1, 0x4b, 0xab,
	0xe9, 0x6a, 0xc3, 0xca, 0x8d, 0x95, 0x77, 0x7e, 0x10, 0xd8, 0x72, 0x16, 0xa3, 0x21, 0x3c, 0xc1,
	0xf4, 0xfc, 0x62, 0x30, 0x4c, 0xf1, 0x23, 0xa6, 0x37, 0x61, 0x65, 0x83, 0x19, 0x84, 0x84, 0xee,
	0xc2, 0x76, 0x3f, 0x4d, 0x70, 0x78, 0x9c, 0x26, 0x43, 0x69, 0xf2, 0x36, 0xa9, 0x41, 0xe8, 0xd3,
	0x6d, 0x68, 0xde, 0xdc, 0xa6, 0xf8, 0x41, 0x3a, 0xaa, 0x2e, 0x1c, 0x84, 0x35, 0x31, 0x70, 0x92,
	0x5c, 0x9e, 0xdc, 0x5e, 0x26, 0xc3, 0x54, 0x3a, 0x82, 0x4d, 0x6a, 0x10, 0xd6, 0x0f, 0xfa, 0xb0,
	0xb3, 0x7e, 0x46, 0xc5, 0x6b, 0x2e, 0xde, 0x0f, 0xd3, 0xf3, 0x14, 0x7b, 0x2c, 0xac, 0x38, 0x30,
	0x8e, 0x42, 0x42, 0xb7, 0xa0, 0x7e, 0x76, 0x79, 0x9d, 0x0c, 0x7b, 0x2c, 0xf4, 0x2c, 0x88, 0xa3,
	0xd0, 0xff, 0xa4, 0x7e, 0x71, 0x7a, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x1c, 0x5f, 0x3c,
	0x90, 0x06, 0x00, 0x00,
}
