// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/message.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Messsage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Messsage) Reset()         { *m = Messsage{} }
func (m *Messsage) String() string { return proto.CompactTextString(m) }
func (*Messsage) ProtoMessage()    {}
func (*Messsage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2c716e67c403b1b, []int{0}
}

func (m *Messsage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Messsage.Unmarshal(m, b)
}
func (m *Messsage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Messsage.Marshal(b, m, deterministic)
}
func (m *Messsage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Messsage.Merge(m, src)
}
func (m *Messsage) XXX_Size() int {
	return xxx_messageInfo_Messsage.Size(m)
}
func (m *Messsage) XXX_DiscardUnknown() {
	xxx_messageInfo_Messsage.DiscardUnknown(m)
}

var xxx_messageInfo_Messsage proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Messsage)(nil), "protos.Messsage")
}

func init() { proto.RegisterFile("protos/message.proto", fileDescriptor_c2c716e67c403b1b) }

var fileDescriptor_c2c716e67c403b1b = []byte{
	// 59 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x03, 0x73, 0x85, 0xd8, 0x20,
	0xa2, 0x4a, 0x5c, 0x5c, 0x1c, 0xbe, 0xa9, 0xc5, 0x60, 0x99, 0x24, 0x88, 0x98, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x7f, 0xd2, 0xac, 0x92, 0x32, 0x00, 0x00, 0x00,
}
